version: '3.7'

services:

  taxi-redis:
    container_name: taxi-redis
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379

  taxi-database:
    container_name: taxi-database
    image: igorzna/postgres:12.1-TAXI-APP
    ports:
      - 5433:5432
    volumes:
      - taxi-database:/var/lib/postgresql/data
    environment:
      - PGDATABASE=taxi
      - PGUSER=taxi
      - PGPASSWORD=taxi
      - PGHOST=taxi-database
      - REDIS_URL=redis://taxi-redis:6379/0

volumes:
  taxi-database:
  media:
  static: